name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove containerd -y  # Remove conflicting package
          sudo apt-get install --no-install-recommends docker.io -y

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: samreenraza40/microarray_data_analysis_scripts
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
