name: Build and Push Docker Image

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: samreenraza40/microarray_data_analysis_scripts
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
