name: Microarray Analysis

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install R and dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y r-base
          mkdir -p ~/R/library

      - name: Install BiocManager
        run: |
          R -e "install.packages('BiocManager', lib='~/R/library')"

      - name: Set R library path
        run: |
          echo '.libPaths("~/R/library")' >> ~/.Rprofile

      - name: Install Bioconductor packages
        run: |
          R -e "BiocManager::install(version = '3.18', dependencies = TRUE)"
          R -e "BiocManager::install(c('GenomicRanges','Biostrings','SummarizedExperiment'),depemdencies = TRUE)"
          R -e "BiocManager::install(c('MatrixGenerics', 'DelayedArray', 'oligoClasses'), dependencies = TRUE)" 
          R -e "BiocManager::install('oligo', dependencies = TRUE)"
          R -e "BiocManager::install('Biobase')"
          R -e "BiocManager::install('multiClust')"
          R -e "BiocManager::install('limma')"
          R -e "BiocManager::install('EnhancedVolcano')"
          R -e "BiocManager::install('diffcoexp')"
          R -e "BiocManager::install('clusterProfiler')"
          R -e "BiocManager::install('enrichplot')"
          R -e "BiocManager::install('pathview')"
          R -e "BiocManager::install('org.Hs.eg.db')"

      - name: Run R scripts
        run: |
          Rscript "Microarray Differential Gene Expression Analysis R scripts/GSE40595_Microarray_data_analysis.R"
          Rscript "Microarray Differential Gene Expression Analysis R scripts/GSE26712_Microarraydataanalysis.R"
          Rscript "Microarray Differential Gene Expression Analysis R scripts/GSE54388_Microarray-data_analysis.R"
