name: Microarray data analysis

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      
      - name: Manually install preprocessCore
        run: |
          git clone https://github.com/bmbolstad/preprocessCore.git
          cd preprocessCore
          R CMD INSTALL --configure-args="--disable-threading"
          
      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::BiocManager
            any::oligo
            any::GenomicRanges
            any::Biostrings
            any::SummarizedExperiment
            any::MatrixGenerics
            any::DelayedArray
            any::oligoClasses
            any::Biobase
            any::multiClust
            any::limma
            any::EnhancedVolcano
            any::diffcoexp
            any::clusterProfiler
            any::enrichplot
            any::pathview
            any::org.Hs.eg.db
            any::pheatmap
            any::ggplot2
            any::amap
            any::ggrepel
            any::openxlsx
            any::readxl
            any::ggridges
            any::R.utils
          
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Running R scripts 
        run: |  
          Rscript scripts/GSE40595_Microarray_data_analysis.R

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: samreenraza40/microarray_data_analysis_scripts
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
  
