name: Microarray data analysis

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest

    steps:
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::BiocManager
            any::oligo
            any::GenomicRanges
            any::Biostrings
            any::SummarizedExperiment
            any::MatrixGenerics
            any::DelayedArray
            any::oligoClasses
            any::Biobase
            any::multiClust
            any::limma
            any::EnhancedVolcano
            any::diffcoexp
            any::clusterProfiler
            any::enrichplot
            any::pathview
            any::org.Hs.eg.db
            any::pheatmap
            any::ggplot2
            any::amap
            any::ggrepel
            any::openxlsx
            any::readxl
            any::ggridges

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Running R scripts 
        run: |  
          Rscript scripts/GSE40595_Microarray_data_analysis.R
          Rscript scripts/GSE26712_Microarraydataanalysis.R
          Rscript scripts/GSE54388_Microarray-dataanalysis.R
          Rscript scripts/GSE18520_Microarraydataanalysis.R
          
