name: Microarray Analysis

on:
  push:
    branches:
      - main

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install R and dependencies
        run: |
          sudo apt update -qq
          sudo apt install -y r-base
          mkdir -p ~/R/library
          R -e "install.packages('BiocManager', lib='~/R/library')"
          R -e "BiocManager::install(version = '3.12', lib='~/R/library')"
          R -e "BiocManager::install(c('MatrixGenerics', 'DelayedArray', 'SummarizedExperiment', 'oligoClasses'), dependencies = TRUE, lib='~/R/library')"
          R -e "BiocManager::install('oligo', dependencies = TRUE, lib='~/R/library')"
          R -e "BiocManager::install('Biobase', lib='~/R/library')"
          R -e "BiocManager::install('multiClust', lib='~/R/library')"
          R -e "BiocManager::install('limma', lib='~/R/library')"
          R -e "BiocManager::install('EnhancedVolcano', lib='~/R/library')"
          R -e "BiocManager::install('GenomicRanges', lib='~/R/library')"
          R -e "BiocManager::install('diffcoexp', lib='~/R/library')"
          R -e "BiocManager::install('clusterProfiler', lib='~/R/library')"
          R -e "BiocManager::install('enrichplot', lib='~/R/library')"
          R -e "BiocManager::install('pathview', lib='~/R/library')
