name: Microarray data analysis

on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Additional steps for Docker setup, R setup, package installation, etc.
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install docker.io -y

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install Packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::BiocManager
            any::oligo
            any::GenomicRanges
            any::Biostrings
            any::SummarizedExperiment
            any::MatrixGenerics
            any::DelayedArray
            any::oligoClasses
            any::Biobase
            any::multiClust
            any::limma
            any::EnhancedVolcano
            any::diffcoexp
            any::clusterProfiler
            any::enrichplot
            any::pathview
            any::org.Hs.eg.db
            any::pheatmap
            any::ggplot2
            any::amap
            any::ggrepel
            any::openxlsx
            any::readxl
            any::ggridges
                
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Running R scripts
        run: |
          R -e 'source("scripts/GSE40595_Microarray_data_analysis.R")'
          R -e 'source("scripts/GSE26712_Microarraydataanalysis.R")'
          R -e 'source("scripts/GSE54388_Microarray-dataanalysis.R")'
          R -e 'source("scripts/GSE18520_Microarraydataanalysis.R")'
          
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfile
          push: true
          tags: samreenraza40/microarray_data_analysis_scripts:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
