name: Microarray data analysis

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging
        run: |
          ls -l /usr/bin/docker*
          sudo which docker
          sudo docker --version

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y containerd.io containerd
          sudo apt-get install -y docker.io
          sudo apt-get install -y containerd.io
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo docker --version

      - name: Pull latest Docker image
        run: |
          docker pull dvcorg/cml:latest

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      # Continue with the rest of your steps...

