name: Microarray data analysis

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    
    steps:          
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        
      - name: Install BiocManager and other required pacakges
        run: |
          R -e 'install.packages("BiocManager")'
          R -e 'BiocManager::install(c("Biostrings", "SummarizedExperiment", "GenomicRanges", "oligoClasses", "GenomeInfoDb"))'
          R -e 'BiocManager::install("oligo", configure.args="--disable-threading", force = TRUE)'
          R -e 'BiocManager::install(c("MatrixGenerics", "DelayedArray", "Biobase", "multiClust", "limma", "EnhancedVolcano", "diffcoexp", "clusterProfiler", "enrichplot", "pathview", "org.Hs.eg.db", "pheatmap", "ggplot2", "amap", "ggrepel", "openxlsx", "readxl", "ggridges", "R.utils"))'

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Running R scripts 
        run: |  
          Rscript scripts/GSE40595_Microarray_data_analysis.R

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: samreenraza40/microarray_data_analysis_scripts
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: dockerfile
  
